// Copyright © 2025–2026 Dankest, LLC
// Based on XChain Platform by Dankest, LLC – https://dankest.llc
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This file is part of XChain Platform. Licensed under the GNU Affero
// General Public License v3.0 or later; see LICENSE.md. A commercial
// license (without AGPL source-disclosure terms) is available -
// contact legal@dankest.llc.

// Demo gated-content fixtures. Short-circuits the live
// `listGatedFiles` / `unlockGatedFileForAddress` flows so the wallet's
// Unlock tab on TokenDetail has something to render even when there's
// no real explorer / on-chain key handoff behind it.
//
// Picked tickers (currently just PEPECREATURE) return a hand-rolled
// group list that mirrors the real protocol shape: single-file group
// + multi-file pack sharing one KEY_HASH, so the UI exercises the
// same code paths as a production unlock. Plaintexts are tiny inline
// fixtures (SVG, text, JSON, fake PDF) so the bundle stays under a few
// KB while still rendering convincingly in the viewer.
//
// Triggering rule: any actionIndex prefixed with `demo:` is handled
// here. Real on-chain action indices are numeric strings, so there's
// no collision risk with a future indexer payload.

const PEPECREATURE_SINGLE_KEY_HASH = '0d6c83a1f1c8e1e9ff77cb2b1b2c3d4e5f60718293a4b5c6d7e8f9001122334455';
const PEPECREATURE_PACK_KEY_HASH   = 'aa11bb22cc33dd44ee55ff667788990011223344556677889900aabbccddeeff';

const VIDEO_NOTICE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 400">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#1E40AF"/>
      <stop offset="100%" stop-color="#7C2D12"/>
    </linearGradient>
  </defs>
  <rect width="600" height="400" fill="url(#bg)"/>
  <circle cx="300" cy="200" r="60" fill="rgba(255,255,255,0.15)"/>
  <polygon points="285,170 285,230 335,200" fill="#FFFFFF"/>
  <text x="300" y="310" font-family="system-ui,sans-serif" font-size="22" font-weight="700" fill="#FFFFFF" text-anchor="middle">Holder-only behind-the-scenes</text>
  <text x="300" y="340" font-family="system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.8)" text-anchor="middle">creature-bts.mp4 · 2:14</text>
</svg>`;

const CREATURE_ART_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400">
  <defs>
    <radialGradient id="halo" cx="50%" cy="40%" r="60%">
      <stop offset="0%" stop-color="#FFFBEB"/>
      <stop offset="100%" stop-color="#16A34A"/>
    </radialGradient>
  </defs>
  <rect width="400" height="400" fill="url(#halo)"/>
  <ellipse cx="200" cy="250" rx="120" ry="80" fill="#15803D" stroke="#052e16" stroke-width="4"/>
  <ellipse cx="200" cy="180" rx="90" ry="80" fill="#16A34A" stroke="#052e16" stroke-width="4"/>
  <ellipse cx="170" cy="170" rx="14" ry="18" fill="#FFFFFF" stroke="#052e16" stroke-width="3"/>
  <ellipse cx="230" cy="170" rx="14" ry="18" fill="#FFFFFF" stroke="#052e16" stroke-width="3"/>
  <circle cx="170" cy="174" r="6" fill="#052e16"/>
  <circle cx="230" cy="174" r="6" fill="#052e16"/>
  <path d="M155 215 Q200 245 245 215" stroke="#052e16" stroke-width="4" fill="none" stroke-linecap="round"/>
  <text x="200" y="370" font-family="Georgia,serif" font-style="italic" font-size="18" fill="#052e16" text-anchor="middle">Pepe Creature · holder edition</text>
</svg>`;

const WELCOME_TEXT = `Welcome, Pepe Creature holder.

This drop unlocks once you hold even a single PEPECREATURE token. The
files in this pack will only ever exist for verified holders. Pass
your token to someone else and they pick up where you left off; the
key handoff happens automatically as part of the SEND transaction.

Inside this pack:
  • creature-art.svg     - high-resolution holder edition art
  • perks.json           - your benefits + perks list
  • holder-magazine.pdf  - issue #1 of the holder zine
  • behind-the-scenes    - short video unlock (separate group)

If you have any questions, find us on the channels listed in the
token's About tab. Welcome to the family.

Kane Mayfield, Pepe Creature Studio
`;

const PERKS_JSON = JSON.stringify({
    tier: 'holder',
    benefits: [
        'Access to the #holders Discord channel',
        'Early access to monthly Pepe drops',
        'Whitelist for next-gen Creature edition',
        '20% off Studio merch (use code CREATURE20)',
        'Voting power on quarterly studio direction polls',
    ],
    expires_at: '2026-12-31T23:59:59Z',
    issued_to: 'pepecreature-holders',
    notes: 'Benefits ride with the token. Sell your token and the next holder inherits these perks automatically.',
}, null, 2);

// Minimal valid 1-page PDF blob (text-only). Generated by hand to keep
// the demo bundle small. Adobe / Chrome / Preview all render this fine.
const HOLDER_PDF = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 320 >>
stream
BT
/F1 22 Tf
72 720 Td
(Pepe Creature Holder Magazine #1) Tj
0 -36 Td
/F1 12 Tf
(A small thank-you to every holder who carried the project this far.) Tj
0 -20 Td
(In this issue: studio interview, upcoming drop calendar,) Tj
0 -20 Td
(and a deep dive on how token-gated content works.) Tj
0 -40 Td
/F1 10 Tf
(Sample document delivered via XChain token-gated content.) Tj
ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000113 00000 n
0000000220 00000 n
0000000590 00000 n
trailer
<< /Size 6 /Root 1 0 R >>
startxref
660
%%EOF`;

const FIXTURES = {
    PEPECREATURE: [
        // Single-file group: behind-the-scenes video. Even though we
        // serve an SVG poster (real video bytes would balloon the
        // bundle), MIME-typing it as `video/mp4` keeps the viewer in
        // its download-link branch so the UX matches a real video
        // drop. Holders see "Download (size)" → grab the file → play.
        {
            keyHash: PEPECREATURE_SINGLE_KEY_HASH,
            encryptionMethod: 1,
            gateTicker: 'PEPECREATURE',
            packMeta: {
                name: 'Behind the scenes',
                description: 'Studio walkthrough video, holders-only.',
            },
            files: [
                {
                    actionIndex: 'demo:pepecreature-bts',
                    name: 'creature-bts.mp4',
                    type: 'video/mp4',
                    title: 'Behind the scenes',
                    status: 'valid',
                    plaintext: VIDEO_NOTICE_SVG,
                    plaintextMime: 'image/svg+xml',
                },
            ],
        },
        // Multi-file pack; exercises the pack rendering path: one
        // shared KEY_HASH, multiple files of different MIME types so
        // every viewer branch (image / text / json / download) lights
        // up after a single unlock.
        {
            keyHash: PEPECREATURE_PACK_KEY_HASH,
            encryptionMethod: 1,
            gateTicker: 'PEPECREATURE',
            packMeta: {
                name: 'Holder pack',
                description: 'Art, perks list, and the issue #1 magazine, all bundled into a single unlock.',
            },
            files: [
                {
                    actionIndex: 'demo:pepecreature-art',
                    name: 'creature-art.svg',
                    type: 'image/svg+xml',
                    title: 'Holder edition art',
                    status: 'valid',
                    plaintext: CREATURE_ART_SVG,
                    plaintextMime: 'image/svg+xml',
                },
                {
                    actionIndex: 'demo:pepecreature-welcome',
                    name: 'welcome.txt',
                    type: 'text/plain',
                    title: 'Welcome letter',
                    status: 'valid',
                    plaintext: WELCOME_TEXT,
                    plaintextMime: 'text/plain',
                },
                {
                    actionIndex: 'demo:pepecreature-perks',
                    name: 'perks.json',
                    type: 'application/json',
                    title: 'Holder perks',
                    status: 'valid',
                    plaintext: PERKS_JSON,
                    plaintextMime: 'application/json',
                },
                {
                    actionIndex: 'demo:pepecreature-magazine',
                    name: 'holder-magazine.pdf',
                    type: 'application/pdf',
                    title: 'Holder Magazine #1',
                    status: 'valid',
                    plaintext: HOLDER_PDF,
                    plaintextMime: 'application/pdf',
                },
            ],
        },
    ],
};

// Index from actionIndex → fixture file so the unlock handler can
// resolve plaintexts in O(1) without iterating every group.
const FIXTURE_BY_INDEX = (() => {
    const out = /** @type {Map<string, any>} */ (new Map());
    for (const groups of Object.values(FIXTURES)) {
        for (const g of groups) {
            for (const f of g.files) {
                out.set(f.actionIndex, f);
            }
        }
    }
    return out;
})();

/**
 * Return the demo-content group list for a tick, mapped into the same
 * shape `listGatedFiles` produces from a real explorer response.
 * Includes a `packMeta` hint so the UI can render a friendlier pack
 * heading + description without needing TIS metadata.
 *
 * @param {string} tick
 * @returns {Array<{
 *   keyHash: string,
 *   encryptionMethod: number,
 *   gateTicker: string,
 *   packMeta?: { name?: string, description?: string },
 *   files: Array<{ actionIndex: string, name: string, type: string | null, title: string | null, status: string | null }>,
 * }>}
 */
export function getDemoGatedGroupsForTick(tick) {
    const fixtures = FIXTURES[String(tick || '').toUpperCase()];
    if (!fixtures) return [];
    return fixtures.map((g) => ({
        keyHash: g.keyHash,
        encryptionMethod: g.encryptionMethod,
        gateTicker: g.gateTicker,
        packMeta: g.packMeta,
        files: g.files.map((f) => ({
            actionIndex: f.actionIndex,
            name: f.name,
            type: f.type,
            title: f.title,
            status: f.status,
        })),
    }));
}

/**
 * Cheap check used by the unlock handler to skip vault/SDK work on
 * demo actionIndices.
 *
 * @param {string | number} actionIndex
 */
export function isDemoGatedActionIndex(actionIndex) {
    return typeof actionIndex === 'string' && actionIndex.startsWith('demo:');
}

/**
 * Return the demo plaintext for a given actionIndex as base64, ready
 * to be returned from the IPC handler. Returns null when the index
 * isn't a demo fixture.
 *
 * @param {string | number} actionIndex
 * @returns {{ plaintextBase64: string, byteLength: number } | null}
 */
export function getDemoGatedPlaintextBase64(actionIndex) {
    const file = FIXTURE_BY_INDEX.get(String(actionIndex));
    if (!file) return null;
    const bytes = Buffer.from(file.plaintext, 'utf8');
    return {
        plaintextBase64: bytes.toString('base64'),
        byteLength: bytes.length,
    };
}
